'use client';
import {useEffect,useRef,useState} from 'react';
import {calcBudget,investmentLevel,markArtifact,projectHealth,matrixTable,DEMAND_LABELS,LEVEL_LABELS} from '../lib/core.js';
import {buildPlanDocument} from '../lib/plan-document.js';
import {paletteFromImage} from '../lib/palette.js';
import {DocumentPreview} from './doc-preview';
import {nextStep} from '../lib/journey.js';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const categories=['Relacionamento','Engajamento','Transformação','Interação 1x1','Níveis de consciência','Autoridade'];
const uid=()=>`item-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function Field({label,children,hint}:any){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Section({title,children,action}:any){return <section className="card"><div className="cardHead"><h3>{title}</h3>{action}</div>{children}</section>}
function Intro({tag,title,text,action}:any){return <div className="sectionIntro"><div><div className="eyebrow">{tag}</div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Text({value}:any){return <div className="fullText">{typeof value==='string'?value:JSON.stringify(value,null,2)}</div>}
function List({title,items}:any){return items?.length?<div className="docList"><h4>{title}</h4><ul>{items.map((x:any,i:number)=><li key={i}>{typeof x==='string'?x:JSON.stringify(x)}</li>)}</ul></div>:null}
function Download({data,name}:any){return <button className="secondary" onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`${name}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}>Exportar</button>}
export function CopyBlock({title,lines,hint}:any){
 const [done,setDone]=useState(false);const text=(lines||[]).join('\n');
 return <div className="copyBlock"><div className="copyBlockHead"><h4>{title}</h4><button className="secondary" disabled={!text} onClick={async()=>{try{await navigator.clipboard.writeText(text);setDone(true);setTimeout(()=>setDone(false),1800)}catch{}}}>{done?'Copiado ✓':'Copiar bloco'}</button></div>{hint&&<small className="muted">{hint}</small>}<pre className="copyBlockText">{text||'—'}</pre></div>;
}
function Requirements({items,title='Informações para este motor',note}:any){
 const done=items.filter((x:any)=>x[1]).length;
 return <div className="enginePrep"><div className="enginePrepHead"><div><small>PRÉ-REQUISITOS</small><b>{title}</b></div><span>{done}/{items.length}</span></div><div className="requirementGrid">{items.map((x:any,i:number)=><div key={i} className={x[1]?'ready':'missing'}><span>{x[1]?'✓':'○'}</span><b>{x[0]}</b></div>)}</div>{note&&<p>{note}</p>}</div>;
}


export function Projects({projects,open,create}:any){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('Todos');
 const stage=(p:any)=>p.commercialStage==='won'?'Cliente':p.commercialStage==='declined'?'Declinado':p.proposal?'Proposta':p.marketingPlan?'Plano':p.approach?'Abordagem':'Prospecção';
 const next=(p:any)=>nextStep(p).label;
 const list=projects.filter((p:any)=>`${p.name} ${p.specialty} ${p.location}`.toLowerCase().includes(query.toLowerCase())&&(filter==='Todos'||stage(p)===filter));
 return <><section className="portfolioHero"><div className="eyebrow">NEXUS MARKETING IA</div><h2>Projetos em um fluxo<br/>simples de trabalho.</h2><p>Abra um projeto e continue exatamente de onde parou.</p><button className="primary" onClick={create}>＋ Criar projeto</button><div className="portfolioDecoration" aria-hidden="true">NXS</div></section>
 <div className="portfolioToolbar"><div><h3>Meus projetos <span>{projects.length}</span></h3><p>Prospecção, fechamento e gestão no mesmo lugar.</p></div><div className="portfolioFilters"><Field label="Buscar projeto"><input type="search" placeholder="Nome, especialidade ou cidade" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Etapa"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Prospecção</option><option>Abordagem</option><option>Plano</option><option>Proposta</option><option>Cliente</option><option>Declinado</option></select></Field></div></div>
 <div className="projectGrid">{list.map((p:any)=>{const h=projectHealth(p);const s=stage(p);return <article className="projectCard" key={p.id}><div className="projectCardTop"><span className="projectMonogram">{p.name.split(' ').slice(0,2).map((s:string)=>s[0]).join('').toUpperCase()}</span><span className={`pill ${s==='Cliente'?'green':s==='Declinado'?'red':'blue'}`}>{s}</span></div><h3>{p.name}</h3><p>{p.specialty||'Briefing ainda não concluído'}</p><span className="projectLocation">{p.location||'Localização a definir'}</span><div className="projectObjective"><small>PRÓXIMO PASSO</small><b>{next(p)}</b></div><div className="projectProgress"><span>Estrutura disponível</span><b>{h.score}%</b></div><div className="progress"><i style={{width:h.score+'%'}}/></div><div className="projectCardFoot"><small>Atualizado {new Date(p.updatedAt).toLocaleDateString('pt-BR')}</small><button className="primary" onClick={()=>open(p.id)}>Continuar →</button></div></article>})}<button className="projectCreateCard" onClick={create}><span>＋</span><b>Novo projeto</b><p>Comece pela prospecção.</p></button></div>{!list.length&&<p role="status">Nenhum projeto encontrado com esses filtros.</p>}</>;
}
export function ProjectDialog({save,close}:any){
 const ref=useRef<HTMLDialogElement>(null);const [name,setName]=useState(''),[objective,setObjective]=useState('Gerar oportunidades qualificadas'),[location,setLocation]=useState('');
 useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous?.focus()},[]);
 return <dialog ref={ref} className="projectDialog" onCancel={e=>{e.preventDefault();close()}} aria-labelledby="project-dialog-title"><form onSubmit={e=>{e.preventDefault();if(name.trim())save({name:name.trim(),objective,location})}}><div className="cardHead"><div><div className="eyebrow">NOVA ÁREA DE TRABALHO</div><h2 id="project-dialog-title">Criar projeto</h2></div><button type="button" className="iconBtn" aria-label="Fechar criação de projeto" onClick={close}>×</button></div><p>Organize os dados e materiais de uma marca em um só lugar.</p><Field label="Nome da marca ou projeto"><input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nexus Digital"/></Field><Field label="Objetivo principal"><input value={objective} onChange={e=>setObjective(e.target.value)}/></Field><Field label="Cidade ou região"><input value={location} onChange={e=>setLocation(e.target.value)}/></Field><div className="buttonRow"><button className="primary" type="submit" disabled={!name.trim()}>Criar projeto</button><button className="secondary" type="button" onClick={close}>Cancelar</button></div></form></dialog>
}
// Perfil do especialista: quem presta o serviço na empresa prospectada. Hipótese para o gestor se preparar.
const SPECIALIST_SECTIONS:[string,[string,string][]][]=[
 ['Quem é',[['nome_ficticio','Nome fictício'],['idade','Idade'],['retrato','Retrato'],['formacao','Formação'],['trajetoria','Trajetória'],['situacao_do_negocio','Situação do negócio'],['como_chegam_clientes_hoje','Como chegam os clientes hoje'],['rotina','Rotina'],['meta_principal','Principal meta'],['sonho','Sonho']]],
 ['Dificuldades, medos e receios',[['maior_dificuldade','Maior dificuldade'],['dificuldades_dia_a_dia','Dificuldades do dia a dia'],['emocoes','Emoções ao vender e divulgar'],['medos','Maiores medos'],['receios_sobre_marketing','Receios sobre marketing, agências e gestores'],['duvidas','Dúvidas antes de investir']]],
 ['O que já tentou e não quer',[['o_que_ja_tentou','O que já tentou'],['frustracoes_com_agencias','Frustrações com quem prometeu e não entregou'],['o_que_nao_quer','O que não quer passar nem fazer']]],
 ['Como ele decide',[['o_que_valoriza','O que valoriza'],['objecoes_para_contratar','Objeções para contratar'],['frases_que_diria','Frases que ele diria']]],
 ['Como conversar com ele',[['como_abordar','Como abordar'],['o_que_evitar_na_conversa','O que evitar na conversa'],['perguntas_para_fazer','Perguntas para a primeira conversa'],['sinais_de_confianca','Sinais de que a conversa vai bem']]]
];
function specialistToText(d:any){
 const out:string[]=[];
 for(const [title,fields] of SPECIALIST_SECTIONS){out.push('## '+title);for(const [k,l] of fields){const v=d?.[k];if(hasValue(v))out.push(l.toUpperCase()+'\n'+(Array.isArray(v)?v.map((x:any)=>'- '+(typeof x==='string'?x:JSON.stringify(x))).join('\n'):String(v)))}}
 return out.join('\n\n');
}
function SpecialistProfile({p,update,run}:any){
 const data=p.specialist;const [notice,setNotice]=useState('');
 const ready=!!(p.name?.trim()&&(p.specialty||p.services||p.products)?.trim());
 const copy=async()=>{try{await navigator.clipboard.writeText(specialistToText(data));setNotice('Perfil copiado.')}catch{setNotice('Não foi possível copiar. Use Exportar.')}};
 return <section className="card specialistCard"><div className="cardHead"><div><div className="eyebrow">ESPECIALISTA</div><h3>Quem presta o serviço nesta empresa</h3></div>{data&&<button className="primary" onClick={()=>run('specialist')}>✦ Gerar novo perfil</button>}</div>
 <p className="muted">Com a empresa e a oferta preenchidas, o Nexus cria o perfil de quem atende e decide: medos, receios, dificuldades e como conversar com essa pessoa. É uma hipótese para você se preparar, não um dado sobre alguém real.</p>
 <Field label="O que você já sabe sobre o especialista (opcional)" hint="Cargo, tempo de mercado, como ele se comporta, o que já disse. Quanto mais real, melhor o perfil."><textarea value={p.expertNotes||''} onChange={e=>update((d:any)=>{d.expertNotes=e.target.value})} placeholder="Ex.: engenheiro civil, dono e único responsável técnico, atende por indicação"/></Field>
 {!data&&<div className="buttonRow"><button className="primary" disabled={!ready} onClick={()=>run('specialist')}>✦ Gerar especialista</button>{!ready&&<span className="muted">Preencha o nome da empresa e o que ela vende ou presta.</span>}</div>}
 {data&&<><div className="personaToolbar"><span className="pill amber">Hipótese de perfil · confirme na conversa</span><button className="secondary" onClick={copy}>Copiar perfil completo</button><Download data={data} name="especialista"/><span role="status">{notice}</span></div>
 {SPECIALIST_SECTIONS.map(([title,fields])=>fields.some(([k])=>hasValue(data[k]))&&<div key={title} className="specialistGroup"><h4 className="specialistTitle">{title}</h4><div className="personaFields">{fields.map(([k,label])=>hasValue(data[k])&&<div key={k} className={Array.isArray(data[k])||String(data[k]||'').length>140?'personaWide':''}><h5>{label}</h5><PersonaValue value={data[k]}/></div>)}</div></div>)}</>}
 </section>;
}
export function BrandBrief({p,update,run,onContinue}:any){
 const set=(k:string,v:any)=>update((d:any)=>{d[k]=v;d.versions={...d.versions,business:(d.versions?.business||0)+1}});
 const input=(k:string,label:string,multiline=false,placeholder='')=><Field key={k} label={label}>{multiline?<textarea value={p[k]||''} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>:<input value={p[k]||''} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>}</Field>;
 const ready=!!(p.name?.trim()&&p.specialty?.trim()&&p.niche?.trim()&&p.location?.trim());
 const uploadLogo=(file?:File)=>{if(!file)return;if(file.size>700000){alert('Use uma logo de até 700 KB para evitar falhas de armazenamento no navegador.');return}const reader=new FileReader();reader.onload=async()=>{const logo=String(reader.result||'');const pal=await paletteFromImage(logo);update((d:any)=>{d.brandLogo=logo;d.brandPalette=pal;d.brandColor=pal.main;d.brandAccent=pal.accent})};reader.readAsDataURL(file)};
 return <><Intro tag="ETAPA 1 DE 5 · PROSPECÇÃO" title="Conheça a empresa e quem presta o serviço." text="Preencha empresa e oferta. Depois gere o perfil do especialista para saber com quem você vai conversar. O restante do fluxo reaproveita estas informações."/>
 <div className="workspaceColumns"><Section title="Empresa">{input('name','Nome da empresa')}{input('specialty','O que ela vende ou presta',true,'Serviços, produtos e especialidades')}{input('niche','Quem costuma comprar',true,'Público, tipo de cliente ou segmento')}{input('description','Contexto do negócio',true,'Resumo objetivo da empresa')}{input('location','Cidade ou região')}</Section><div className="stack"><Section title="Oferta">{input('services','Serviços principais',true)}{input('products','Produtos, se houver',true)}{input('offers','Diferenciais, garantias ou condições conhecidas',true)}{input('objective','Objetivo desta prospecção')}</Section><Section title="Identidade"><div className="brandIdentityRow"><div className="brandLogoPreview">{p.brandLogo?<img src={p.brandLogo} alt="Logo do prospect"/>:<span>LOGO</span>}</div><div><Field label="Logo da empresa" hint="PNG, JPG ou SVG, até 700 KB. As cores do plano e da proposta saem dela."><input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={e=>uploadLogo(e.target.files?.[0])}/></Field>{p.brandLogo&&<button className="dangerText" onClick={()=>set('brandLogo','')}>Remover logo</button>}</div></div><div className="form2"><Field label="Cor principal" hint="Títulos e fundos do documento."><input type="color" value={/^#[0-9a-f]{6}$/i.test(p.brandColor||'')?p.brandColor:'#0f2747'} onChange={e=>set('brandColor',e.target.value)}/></Field><Field label="Cor de destaque" hint="Faixas, ícones e botão do WhatsApp."><input type="color" value={/^#[0-9a-f]{6}$/i.test(p.brandAccent||'')?p.brandAccent:'#d98a0b'} onChange={e=>set('brandAccent',e.target.value)}/></Field></div>{input('tone','Tom de voz')}{input('contactDestination','Site, Instagram, Google ou WhatsApp',true)}</Section></div></div>
 <SpecialistProfile p={p} update={update} run={run}/>
 <div className="flowFooter"><div><b>{ready?'Empresa pronta':'Complete os campos essenciais'}</b><span>{ready?'A próxima etapa é preparar a abordagem.':'Nome, oferta, público e localização são obrigatórios.'}</span></div><button className="primary" disabled={!ready} onClick={onContinue}>Salvar e seguir →</button></div>
 </>;
}
export function MediaPlanning({p,update,onContinue}:any){
 const b={...p.budget,gbpPct:p.budget?.gbpPct??20};const total=calcBudget(b.amount,b.demand,b.level,b.gbpPct,b.googleOverride);
 const set=(k:string,v:any)=>update((d:any)=>{d.budget={...d.budget,[k]:v};d.mediaPlanConfirmed=false;if(k==='amount')d.budget.level=investmentLevel(v)});
 const finish=()=>{update((d:any)=>{d.mediaPlanConfirmed=true},'Distribuição de investimento confirmada');onContinue?.()};
 return <><Intro tag="ETAPA 4 DE 5 · GESTÃO" title="Distribua o investimento sem precisar dominar mídia paga." text="Informe o orçamento e como a demanda acontece. O Nexus aplica a matriz e mostra a divisão."/>
 <div className="workspaceColumns"><Section title="Defina o cenário"><Field label="Investimento mensal disponível (R$)"><input type="number" min="0" step="50" value={b.amount||''} onChange={e=>set('amount',Math.max(0,Number(e.target.value)))}/></Field><Field label="Como as pessoas chegam até esta empresa?"><select value={b.demand} onChange={e=>set('demand',e.target.value)}><option value="busca">Já estão procurando pelo serviço</option><option value="descoberta">Precisamos despertar interesse</option><option value="hibrido">Os dois cenários</option></select></Field><div className="matrixSummary"><span>Google <b>{total.googlePct}%</b></span><span>Meta <b>{total.metaPct}%</b></span><span>GBP <b>{total.gbpPct}% do Google</b></span></div><details className="advanced"><summary>Ajustes avançados</summary><Field label={`Google: ${total.googlePct}% · Meta: ${total.metaPct}%`}><input type="range" min="0" max="100" value={total.googlePct} onChange={e=>set('googleOverride',Number(e.target.value))}/></Field><Field label={`Presença local / GBP: ${total.gbpPct}% da verba Google`} hint="O padrão do Nexus é 20% da parcela destinada ao Google."><input type="range" min="0" max="100" value={total.gbpPct} onChange={e=>set('gbpPct',Number(e.target.value))}/></Field><button className="secondary" onClick={()=>update((d:any)=>{d.budget={...d.budget,googleOverride:null,gbpPct:20}})}>Restaurar recomendação</button></details></Section><div className="stack"><Section title="Distribuição sugerida"><div className="allocationTotal"><small>INVESTIMENTO TOTAL</small><b>{money.format(total.total)}</b></div><div className="allocationBar"><span style={{width:total.googlePct+'%'}}/><span style={{width:total.metaPct+'%'}}/></div><div className="allocationTiles"><div><span>Google · {total.googlePct}%</span><b>{money.format(total.google)}</b></div><div><span>Meta · {total.metaPct}%</span><b>{money.format(total.meta)}</b></div></div><div className="budgetMini"><div><small>Perfil da Empresa / GBP · {total.gbpPct}% do Google</small><b>{money.format(total.gbp)}</b></div><div><small>Demais Google Ads · {total.adsPct}% do Google</small><b>{money.format(total.ads)}</b></div></div></Section><Section title="Campanhas sugeridas"><List items={total.campaigns}/></Section></div></div>
 <Section title="Matriz estratégica completa" action={<span className="pill blue">Seu cenário: {DEMAND_LABELS[b.demand]||b.demand} · {LEVEL_LABELS[b.level||investmentLevel(b.amount)]}</span>}>
  <p className="muted">As nove combinações da matriz de referência (3 cenários × 3 faixas de investimento). A linha destacada é a do seu cenário.</p>
  <div className="matrixTableWrap"><table className="matrixTable"><thead><tr><th>Cenário</th><th>Faixa de investimento</th><th>Google</th><th>Meta</th><th>Campanhas sugeridas</th><th>Nº</th><th>Conversão (matriz)</th></tr></thead><tbody>{matrixTable().map(r=><tr key={r.demand+r.level} className={r.demand===b.demand&&r.level===(b.level||investmentLevel(b.amount))?'active':''}><td>{r.demandLabel}</td><td>{r.levelLabel}</td><td>{r.google}%</td><td>{r.meta}%</td><td><div className="tagRow">{r.campaigns.map((c:string)=><span key={c}>{c}</span>)}</div></td><td>{r.count}</td><td>{r.conversion}%</td></tr>)}</tbody></table></div>
  <div className="matrixNotes"><div><b>Presença local / GBP</b><span>Dentro da parcela Google, {total.gbpPct}% vai para o Perfil da Empresa (padrão do Nexus: 20%). Ajustável em "Ajustes avançados".</span></div><div><b>Audiência · Ebook do curso</b><span>Para crescer a audiência, invista de 10% a 30% da verba de marketing. Entre públicos frios e quentes, uma divisão igual (50% / 50%) costuma ser suficiente, conforme o tamanho da marca.</span></div></div>
 </Section>
 <div className="flowFooter"><div><b>{total.total>0?'Distribuição pronta':'Informe o orçamento'}</b><span>{total.total>0?'Depois disso, o foco passa a ser acompanhar resultado.':'O Nexus não assume uma verba sem você informar.'}</span></div><button className="primary" disabled={total.total<=0} onClick={finish}>Salvar e ir para resultados →</button></div>
 </>;
}
export function PlanWorkspace({p,update,run,onContinue,settings}:any){
 const data=p.marketingPlan; const ai=p.aiInputs||{};
 const [preview,setPreview]=useState(false);
 const setAI=(k:string,v:any)=>update((d:any)=>{d.aiInputs={...(d.aiInputs||{}),[k]:v}});
 const material=[
  ['Empresa e oferta',!!(p.name&&p.location&&(p.specialty||p.services||p.products))],
  ['Contexto da prospecção',!!(ai.planApproachContext||p.approach)?.toString().trim()],
  ['Destinatário',!!(ai.planRecipientProfile||ai.decisionMakerContext||ai.prospectOwner)?.toString().trim()],
  ['Identidade',!!(p.brandLogo||p.brandColor)],
  ['Condições conhecidas',!!(ai.operationalDetails||p.offers)?.toString().trim()],
  ['Contato para assinatura',!!((ai.signerName||settings?.managerName||'').trim()&&(ai.signerWhatsapp||settings?.agencyWhatsapp||'').trim())]
 ];
 const hasClient=!!(data?.client&&(data.client.personaName||data.client.summary||data.client.obstacle||(data.client.fears||[]).length||(data.client.objections||[]).length));
 const hasAwareness=Array.isArray(data?.awareness)&&data.awareness.length>0;
 const omitted:string[]=Array.isArray(data?.omittedSections)?data.omittedSections.filter((x:any)=>typeof x==='string'&&x.trim()):[];
 const hasPositioning=!!(data?.positioning&&((data.positioning.commitments||[]).length||(data.positioning.fearResponses||[]).length));
 let pageNo=0;
 const page=(title:string,children:any)=>{const n=String(++pageNo).padStart(2,'0');return <section className="planPage"><div className="planPageNo">{n}</div><div><small>PLANO DE MARKETING</small><h3>{title}</h3>{children}</div></section>};
 return <><Intro tag="ETAPA 3 DE 5 · PROSPECÇÃO" title="Transforme o diagnóstico em um plano apresentável." text="O Nexus usa o briefing e a abordagem. Complete somente o contexto comercial que ainda falta." action={<button className="primary" onClick={()=>run('marketingPlan',{context:p.planContext,manager:settings})}>✦ {data?'Gerar nova versão':'Gerar plano'}</button>}/>
 <Requirements items={material} title="Informações reunidas" note="Itens opcionais ausentes não travam a geração; o Nexus simplesmente não inventa o que não foi informado."/>
 <details className="contextDetails" open={!data}><summary>Completar informações específicas do plano</summary><div className="form2"><Field label="Contexto da prospecção"><textarea value={ai.planApproachContext||''} onChange={e=>setAI('planApproachContext',e.target.value)} placeholder="Contato frio, conversa anterior, indicação, o que já foi dito..."/></Field><Field label="Quem receberá o material"><textarea value={ai.planRecipientProfile||''} onChange={e=>setAI('planRecipientProfile',e.target.value)} placeholder="Dono, gerente, o que valoriza, o que já tentou, o que incomoda..."/></Field></div><Field label="Condições atuais conhecidas" hint="Garantia, taxa de visita, horários, área atendida, formas de pagamento. Se não souber, deixe em branco."><textarea value={ai.operationalDetails||''} onChange={e=>setAI('operationalDetails',e.target.value)}/></Field><Field label="Outros materiais ou informações"><textarea value={ai.additionalMaterials||p.planContext||''} onChange={e=>{setAI('additionalMaterials',e.target.value);update((d:any)=>{d.planContext=e.target.value})}} placeholder="Avaliações, prints, dados internos, observações..."/></Field><div className="form2"><Field label="Nome para assinatura"><input value={ai.signerName||settings?.managerName||''} onChange={e=>setAI('signerName',e.target.value)}/></Field><Field label="Cargo / assinatura"><input value={ai.signerRole||settings?.managerSpecialty||''} onChange={e=>setAI('signerRole',e.target.value)}/></Field></div><Field label="WhatsApp com DDD"><input value={ai.signerWhatsapp||settings?.agencyWhatsapp||''} onChange={e=>setAI('signerWhatsapp',e.target.value)} placeholder="15999999999"/></Field><Field label="Convite final opcional"><textarea value={ai.invitationText||''} onChange={e=>setAI('invitationText',e.target.value)} placeholder="Se deixar vazio, o próprio prompt escreve o convite."/></Field></details>
 {!data?<section className="empty"><h3>O plano ainda não foi gerado.</h3><p>Quanto mais itens acima estiverem preenchidos, mais específico será o documento. Você pode gerar mesmo com itens opcionais ausentes.</p></section>:<div className="planPages">
 {omitted.length>0&&<div className="planNotice" role="status"><b>O plano deixou de fora o que não tinha material</b><span>{omitted.join(' · ')}</span><small>Preencha mais informações acima e gere uma nova versão para completá-lo. O Nexus não inventa o que não foi informado.</small></div>}
 {page('Capa',<>{p.brandLogo&&<img className="planClientLogo" src={p.brandLogo} alt="Logo do cliente"/>}<h2>{data.cover?.company||p.name}</h2><p>{data.cover?.objective}</p><div className="tagRow"><span>{data.cover?.city}</span><span>{data.cover?.period}</span><span>{data.cover?.conversion}</span></div></>)}
 {page('O que este plano propõe',<><p>{data.proposal?.text}</p>{data.proposal?.communicationPromise&&<blockquote className="planHighlight">{data.proposal.communicationPromise}</blockquote>}<div className="planRows">{(data.proposal?.workstreams||[]).map((x:any,i:number)=><div key={i}><b>{x.channel}</b><span>{x.audience}</span><p>{x.role}</p></div>)}</div></>)}
 {(data.marketContext?.facts?.length||data.marketContext?.practicalNote)&&page('Contexto de mercado',<><div className="planFacts">{(data.marketContext?.facts||[]).map((x:any,i:number)=><div key={i}><b>{x.value}</b><span>{x.label}</span><small>{x.note}</small></div>)}</div><p>{data.marketContext?.practicalNote}</p></>)}
 {hasClient&&page('Quem é o cliente',<><h4>{data.client?.personaName}</h4><p>{data.client?.summary}</p><List title="Medos" items={data.client?.fears}/><List title="Objeções" items={data.client?.objections}/><List title="O que já tentou" items={data.client?.previousAttempts}/><small className="muted">{data.client?.hypothesisNotice}</small></>)}
 {hasAwareness&&page('Os momentos até a contratação',<div className="awarenessList">{(data.awareness||[]).map((x:any,i:number)=><div key={i}><span>{i+1}</span><div><b>{x.stage}</b><p>{x.message}</p><small>{x.channel}{x.searches?.length?' · '+x.searches.join(' · '):''}</small></div></div>)}</div>)}
 {hasPositioning&&page('Posicionamento',<><List title="Compromissos de atendimento" items={data.positioning?.commitments}/><div className="planRows">{(data.positioning?.fearResponses||[]).map((x:any,i:number)=><div key={i}><b>{x.fearOrObjection}</b><p>{x.response}</p></div>)}</div></>)}
 {(data.channels||[]).length>0&&page('Canal por canal',<div className="planChannelGrid">{(data.channels||[]).map((x:any,i:number)=><div key={i}><h4>{x.name}</h4><p>{x.summary}</p><List items={x.items}/>{x.example&&<div className="planExample">{x.example}</div>}</div>)}</div>)}
 {((data.salesFlow?.steps||[]).length>0||(data.salesFlow?.quickReplies||[]).length>0)&&page('Onde a venda acontece',<><div className="salesFlow">{(data.salesFlow?.steps||[]).map((x:string,i:number)=><div key={i}><span>{i+1}</span><b>{x}</b></div>)}</div><List title="Respostas rápidas" items={data.salesFlow?.quickReplies}/></>)}
 {((data.activation?.timeline||[]).length>0||(data.activation?.indicators||[]).length>0)&&page('Ordem sugerida de ativação',<><div className="activationGrid">{(data.activation?.timeline||[]).map((x:any,i:number)=><div key={i}><b>{x.period}</b><List items={x.actions}/></div>)}</div><List title="Indicadores para acompanhar" items={data.activation?.indicators}/></>)}
 {(data.invitation?.text||data.invitation?.whatsappNumber||data.invitation?.signature)&&page(data.invitation?.title||'Se quiser conversar sobre isso',<><p>{data.invitation?.text}</p>{data.invitation?.whatsappNumber&&<div className="planContact"><b>WhatsApp</b><span>{data.invitation.whatsappNumber}</span><small>{data.invitation.whatsappMessage}</small></div>}<p><b>{data.invitation?.signature}</b></p></>)}
 <div className="planActions"><button className="secondary" onClick={()=>setPreview(true)}>Ver e exportar PDF</button><button className="primary" onClick={onContinue}>Continuar para proposta →</button>{data.sendSeparately?.length>0&&<span>Enviar à parte: {data.sendSeparately.join(', ')}</span>}</div>
 </div>}
 {preview&&data&&<DocumentPreview title={`Plano de marketing · ${p.name||'Projeto'}`} filename={`plano-${String(p.name||'projeto').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}`} html={buildPlanDocument(p,data,{signer:{name:ai.signerName||settings?.managerName,role:ai.signerRole||settings?.managerSpecialty,whatsapp:ai.signerWhatsapp||settings?.agencyWhatsapp}}).html} onClose={()=>setPreview(false)}/>}
 </>;
}
// Estrutura do prompt "Criador de Persona" (curso): tudo aparece expandido, na ordem do prompt.
const PERSONA_SECTIONS:[string,[string,string][]][]=[
 ['Retrato',[['nome','Nome fictício'],['idade','Idade'],['descricao_breve','Breve descrição'],['formacao','Formação'],['profissao','Profissão'],['situacao_profissional','Situação profissional'],['situacao_financeira','Situação financeira'],['estado_civil','Estado civil'],['familia','Família'],['momento_atual','Momento atual da vida'],['sonho_principal','Principal sonho'],['meta_principal','Principal meta'],['localizacao','Localização geográfica']]],
 ['Problema e obstáculo',[['problema_principal','Problema principal'],['obstaculo_principal','Principal obstáculo']]],
 ['Emoções, medos e relacionamentos',[['emocoes','5 principais emoções'],['medos','5 maiores medos'],['medos_relacionamentos','5 maneiras pelas quais os medos afetam os relacionamentos'],['frases_ofensivas','5 frases conversacionais ofensivas']]],
 ['Passado e o que rejeita',[['tentativas_passadas','O que já tentou no passado'],['trechos_passado','5 trechos sobre o passado'],['o_que_nao_quer_fazer','O que não quer fazer'],['trechos_nao_quer','5 trechos sobre o que não quer'],['impacto_relacionamentos','Impacto nos relacionamentos e na vida pessoal'],['culpa_em_quem','Quem culpa']]],
 ['Decisão de compra',[['objecoes','5 maiores objeções'],['como_encorajar_sonhos','Encorajar sonhos'],['como_justificar_erros','Justificar erros'],['como_aliviar_medos','Aliviar medos'],['como_confirmar_suspeitas','Confirmar suspeitas ("Eu sabia")'],['culpados_percebidos','Apontar culpados']]]
];
const AWARENESS:[string,string][]=[['totalmente_inconsciente','1. Totalmente inconsciente'],['consciente_problema','2. Consciente do problema'],['consciente_solucao','3. Consciente da solução'],['consciente_produto','4. Consciente do produto'],['totalmente_consciente','5. Totalmente consciente']];
const AWARENESS_FIELDS:[string,string][]=[['pensa','Pensa'],['sente','Sente'],['percebe','Percebe'],['sabe','Sabe'],['nao_sabe','Ainda não sabe'],['duvidas','Dúvidas'],['comportamento','Comportamento'],['o_que_avanca','O que faz avançar']];
const DEEPDIVE:[string,string][]=[['dificuldades','5 dificuldades'],['medos_extra','5 medos'],['desejos','5 desejos'],['historias_constrangedoras','5 histórias constrangedoras'],['pensamentos_recorrentes','5 pensamentos recorrentes'],['pensamentos_maldosos','5 pensamentos maldosos'],['segredos','5 segredos que esconde do cônjuge e até do terapeuta']];
const hasValue=(v:any)=>Array.isArray(v)?v.length>0:v!=null&&String(v).trim()!=='';
const asLines=(v:any)=>Array.isArray(v)?v.map((x:any)=>typeof x==='string'?x:JSON.stringify(x)).join('\n'):typeof v==='string'?v:v==null?'':JSON.stringify(v,null,2);
function PersonaValue({value}:any){return Array.isArray(value)?<ul className="personaList">{value.map((x:any,i:number)=><li key={i}>{typeof x==='string'?x:JSON.stringify(x)}</li>)}</ul>:<Text value={value}/>}
export function personaToText(d:any){
 const out:string[]=[];
 const put=(label:string,v:any)=>{if(hasValue(v))out.push(label.toUpperCase()+'\n'+(Array.isArray(v)?v.map((x:any)=>'- '+(typeof x==='string'?x:JSON.stringify(x))).join('\n'):String(v)))};
 for(const [title,fields] of PERSONA_SECTIONS){out.push('## '+title);for(const [k,l] of fields)put(l,d?.[k])}
 out.push('## 5 níveis de consciência (Eugene Schwartz)');
 for(const [k,l] of AWARENESS){const st=d?.niveis_consciencia?.[k];if(!st)continue;out.push('### '+l);for(const [f,fl] of AWARENESS_FIELDS)put(fl,st[f])}
 if(d?.exploracao){out.push('## Aprofundamento: dores, medos, desejos e objeções');for(const [k,l] of DEEPDIVE)put(l,d.exploracao[k])}
 return out.join('\n\n');
}
export function PersonaWorkspace({p,update,run,onContinue,continueLabel='Continuar →'}:any){
 const data=p.persona;const [editing,setEditing]=useState(false);const [notice,setNotice]=useState('');const saved=p.personas||[];
 const edit=(k:string,v:any)=>update((d:any)=>{d.persona={...d.persona,[k]:v};markArtifact(d,'persona')});
 const editValue=(k:string,v:string)=>edit(k,Array.isArray(data[k])?v.split('\n'):v);
 const editAw=(stage:string,f:string,v:string)=>update((d:any)=>{d.persona.niveis_consciencia={...d.persona.niveis_consciencia,[stage]:{...d.persona.niveis_consciencia?.[stage],[f]:v}};markArtifact(d,'persona')});
 const setBrand=(k:string,v:string)=>update((d:any)=>{d[k]=v});
 const finishEditing=()=>{update((d:any)=>{for(const k of Object.keys(d.persona||{}))if(Array.isArray(d.persona[k]))d.persona[k]=d.persona[k].filter((x:any)=>String(x).trim()!=='')});setEditing(false)};
 const known=new Set<string>([...PERSONA_SECTIONS.flatMap(([,f])=>f.map(x=>x[0])),'niveis_consciencia','exploracao']);
 const others=data?Object.entries(data).filter(([k,v])=>!known.has(k)&&hasValue(v)):[];
 const copyAll=async()=>{try{await navigator.clipboard.writeText(personaToText(data));setNotice('Persona completa copiada.')}catch{setNotice('Não foi possível copiar. Use Exportar.')}};
 if(!data)return <><Intro tag="PROSPECÇÃO · PERSONA" title="Quem você quer alcançar?" text="Um clique e a persona sai completa: retrato, medos, objeções e os 5 níveis de consciência."/>
  <section className="card personaStart"><div className="eyebrow">PESQUISA DE PERSONA</div><h3>Qual é o nicho sobre o qual você deseja fazer a pesquisa de mercado e o mapeamento de persona?</h3><p className="muted">É a pergunta inicial do prompt. A persona representa quem compra (o público-alvo), não a sua especialidade; a especialidade só dá contexto.</p>
  <div className="form2"><Field label="Público-alvo / nicho de clientes"><input value={p.niche||''} onChange={e=>setBrand('niche',e.target.value)} placeholder="Ex.: síndicos e administradoras de condomínios"/></Field><Field label="Especialidade (o que o negócio faz)"><input value={p.specialty||''} onChange={e=>setBrand('specialty',e.target.value)} placeholder="Ex.: engenharia diagnóstica"/></Field></div>
  <Requirements items={[['Público-alvo / nicho',!!p.niche?.trim()]]} title="Para criar a persona" note="O Nexus usa também descrição, serviços e localização do projeto, quando existirem."/>
  <div className="buttonRow"><button className="primary" disabled={!p.niche?.trim()} onClick={()=>run('persona')}>✦ Criar persona</button><button className="secondary" onClick={()=>{update((d:any)=>{d.persona={nome:'Nova persona'};markArtifact(d,'persona')});setEditing(true)}}>Cadastrar manualmente</button></div></section></>;
 return <><Intro tag="PROSPECÇÃO · PERSONA" title={data.nome||'Persona'} text="Persona completa, na ordem do prompt. Tudo está aberto: leia, edite ou copie." action={<button className="primary" onClick={()=>run('persona')}>✦ Criar nova persona</button>}/>
 <div className="personaToolbar"><Field label="Persona ativa"><select value="" onChange={e=>{if(e.target.value)update((d:any)=>{d.persona=JSON.parse(JSON.stringify(saved.find((x:any)=>x.id===e.target.value).data));markArtifact(d,'persona')},'Persona selecionada')}}><option value="">{data.nome||'Selecione uma persona salva'}</option>{saved.map((x:any)=><option key={x.id} value={x.id}>{x.data.nome} — {x.data.profissao}</option>)}</select></Field>
 <button className="secondary" onClick={()=>editing?finishEditing():setEditing(true)}>{editing?'Concluir edição':'Editar'}</button>
 <button className="secondary" onClick={()=>update((d:any)=>{d.personas=[...(d.personas||[]),{id:uid(),data:JSON.parse(JSON.stringify(d.persona))}]},'Persona salva na biblioteca')}>Salvar na biblioteca</button>
 <button className="secondary" onClick={copyAll}>Copiar persona completa</button><Download data={data} name="persona"/><span className="pill amber">Hipótese de público · valide com clientes</span><span role="status">{notice}</span></div>
 {PERSONA_SECTIONS.map(([title,fields])=><Section key={title} title={title}><div className="personaFields">{fields.map(([k,label])=>(editing||hasValue(data[k]))&&<div key={k} className={Array.isArray(data[k])||String(data[k]||'').length>140?'personaWide':''}>{editing?<Field label={label}><textarea value={asLines(data[k])} onChange={e=>editValue(k,e.target.value)}/></Field>:<><h4>{label}</h4><PersonaValue value={data[k]}/></>}</div>)}</div></Section>)}
 <Section title="5 níveis de consciência · Eugene Schwartz"><div className="awarenessGrid">{AWARENESS.map(([k,label])=>{const st=data.niveis_consciencia?.[k];return (st||editing)?<div key={k} className="awarenessCard"><h4>{label}</h4><div className="personaFields">{AWARENESS_FIELDS.map(([f,fl])=>(editing||hasValue(st?.[f]))&&<div key={f}>{editing?<Field label={fl}><textarea value={asLines(st?.[f])} onChange={e=>editAw(k,f,e.target.value)}/></Field>:<><h5>{fl}</h5><Text value={st[f]}/></>}</div>)}</div></div>:null})}</div></Section>
 {others.length>0&&<Section title="Outros campos">{others.map(([k,v])=><div key={k}><h4>{k.replaceAll('_',' ')}</h4><PersonaValue value={v}/></div>)}</Section>}
 {data.exploracao?<Section title="Aprofundamento: dores, medos, desejos e objeções" action={<button className="secondary" onClick={()=>run('deepDive')}>Atualizar aprofundamento</button>}><div className="personaFields">{DEEPDIVE.map(([k,label])=>hasValue(data.exploracao[k])&&<div key={k} className="personaWide"><h4>{label}</h4><PersonaValue value={data.exploracao[k]}/></div>)}</div></Section>
 :<section className="card deepDiveAsk"><h3>Você gostaria de levantar informações sobre medos, dores, desejos e objeções dessa persona?</h3><p className="muted">Gera 5 dificuldades, 5 medos, 5 desejos, 5 histórias constrangedoras, 5 pensamentos recorrentes, 5 pensamentos maldosos e 5 segredos, específicos para esta persona.</p><button className="primary" onClick={()=>run('deepDive')}>✦ Sim, aprofundar</button></section>}
 <div className="flowFooter"><div><b>Persona pronta</b><span>Ela alimenta o plano de marketing, o conteúdo RETINA e os anúncios.</span></div><button className="primary" onClick={onContinue}>{continueLabel}</button></div></>;
}
export function ContentWorkspace({p,update,run,onContinue}:any){
 const [selected,setSelected]=useState<number|null>(null),[filter,setFilter]=useState('Todas'),[notice,setNotice]=useState('');const items=p.content?.items||[];const item=selected===null?null:items[selected];const ai=p.aiInputs||{};
 const edit=(k:string,v:any)=>update((d:any)=>{d.content.items[selected!][k]=v});
 const setAI=(k:string,v:any)=>update((d:any)=>{d.aiInputs={...(d.aiInputs||{}),[k]:v}});
 const field=(k:string,label:string,multiline=true)=><Field key={k} label={label}>{multiline?<textarea className={k==='script'?'scriptEditor':''} value={item[k]||''} onChange={e=>edit(k,e.target.value)}/>:<input value={item[k]||''} onChange={e=>edit(k,e.target.value)}/>}</Field>;
 const ready=!!(ai.creatorName?.trim()&&p.niche?.trim()&&p.persona);
 return <><Intro tag="04 / CONTEÚDO RETINA" title="Conteúdo pronto, não apenas ideias." text="O motor usa o prompt RETINA completo e só roda depois de saber quem cria, qual é o nicho e qual persona queremos alcançar." action={<button className="primary" disabled={!ready} onClick={()=>{setSelected(null);run('content')}}>✦ {p.content?'Gerar nova versão':'Gerar 6 conteúdos'}</button>}/>
 <Section title="Antes de gerar"><Field label="Nome de quem cria os conteúdos"><input value={ai.creatorName||''} onChange={e=>setAI('creatorName',e.target.value)} placeholder="Pessoa, especialista ou marca que aparecerá no conteúdo"/></Field><Requirements items={[[ 'Responsável pelo conteúdo',!!ai.creatorName?.trim()],['Nicho de mercado',!!p.niche?.trim()],['Persona detalhada',!!p.persona]]} note="O Nexus reaproveita a persona do projeto automaticamente."/></Section>
 <div className="retinaGuide">{categories.map((c,i)=><div key={c}><b>{'RETINA'[i]}</b><span>{c}</span></div>)}</div>{!items.length?<section className="empty"><h3>Seu próximo conteúdo começa na persona.</h3><p>Complete os três pré-requisitos e gere seis peças completas, uma para cada função do RETINA.</p></section>:item?<><button className="secondary backButton" onClick={()=>setSelected(null)}>← Todos os conteúdos</button><Section title={item.title} action={<button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText([item.title,item.hook,item.script,item.igCaption].join('\n\n'));setNotice('Conteúdo copiado.')}catch{setNotice('Não foi possível copiar. Use a exportação.')}}}>Copiar conteúdo</button>}><span role="status">{notice}</span><div className="form2">{field('title','Título',false)}<Field label="Categoria RETINA"><input value={item.category||''} readOnly/></Field></div><div className="form2">{field('format','Formato',false)}<Field label="Status"><select value={item.status||'Rascunho'} onChange={e=>edit('status',e.target.value)}><option>Rascunho</option><option>Em revisão</option><option>Aprovado</option><option>Publicado</option></select></Field></div>{field('idea','Ideia central')}{field('hook','Gancho')}{field('script','Roteiro completo')}{field('igCaption','Legenda')}<div className="form2">{field('dorDesejo','Dor ou desejo')}{field('objecaoDuvida','Objeção ou dúvida')}</div>{field('objetivoRetina','Objetivo dentro do RETINA')}<div className="form2"><Field label="Data prevista"><input type="date" value={item.scheduledDate||''} onChange={e=>edit('scheduledDate',e.target.value)}/></Field><Field label="Canal"><select value={item.channel||'Instagram'} onChange={e=>edit('channel',e.target.value)}><option>Instagram</option><option>Facebook</option><option>LinkedIn</option><option>GBP</option></select></Field></div></Section></>:<><div className="portfolioToolbar"><Field label="Filtrar categoria"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todas</option>{items.map((x:any,i:number)=><option key={i}>{x.category}</option>)}</select></Field><Download data={p.content} name="conteudo-retina"/></div><div className="contentGrid">{items.map((x:any,i:number)=>(filter==='Todas'||filter===x.category)&&<Section key={i} title={x.title}><span className="pill blue">{x.category}</span><p><b>{x.hook}</b></p><p>{x.idea}</p><div className="tagRow"><span>{x.format}</span><span>{x.status||'Rascunho'}</span></div><button className="primary" onClick={()=>setSelected(i)}>Abrir roteiro e editar →</button></Section>)}</div></>}{items.length>0&&selected===null&&<div className="flowFooter"><div><b>Conteúdo estruturado</b><span>Agora escolha onde a empresa vai anunciar.</span></div><button className="primary" onClick={onContinue}>Continuar para anúncios →</button></div>}</>;
}
export function CalendarWorkspace({p,update}:any){
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[query,setQuery]=useState('Todos'),[title,setTitle]=useState('');
 const items=[...(p.content?.items||[]).map((x:any,i:number)=>({...x,index:i,kind:'content'})),...(p.calendarItems||[]).map((x:any,i:number)=>({...x,index:i,kind:'calendar'}))];
 const edit=(x:any,k:string,v:any)=>update((d:any)=>{(x.kind==='content'?d.content.items:d.calendarItems)[x.index][k]=v});
 const filtered=items.filter(x=>(!x.scheduledDate||x.scheduledDate.startsWith(month))&&(query==='Todos'||(x.status||'Rascunho')===query)).sort((a,b)=>(a.scheduledDate||'9999').localeCompare(b.scheduledDate||'9999'));
 return <><Intro tag="05 / EXECUÇÃO" title="O que vai ao ar, e quando." text="Organize produção e revisão por projeto. As datas registram o planejamento editorial."/><div className="calendarFilters"><Field label="Mês"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field><Field label="Status"><select value={query} onChange={e=>setQuery(e.target.value)}><option>Todos</option><option>Rascunho</option><option>Em revisão</option><option>Aprovado</option><option>Publicado</option></select></Field></div><Section title="Adicionar publicação"><form className="calendarAdd" onSubmit={e=>{e.preventDefault();if(title.trim()){update((d:any)=>{d.calendarItems=[...(d.calendarItems||[]),{id:uid(),title:title.trim(),status:'Rascunho',channel:'Instagram',scheduledDate:''}]});setTitle('')}}}><Field label="Título da publicação"><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><button className="primary">Adicionar</button></form></Section><div className="calendarList">{filtered.map(x=><article className="card calendarRow" key={`${x.kind}-${x.index}`}><div><small>{x.category||'PUBLICAÇÃO'}</small><h3>{x.title}</h3></div><Field label="Data prevista"><input type="date" value={x.scheduledDate||''} onChange={e=>edit(x,'scheduledDate',e.target.value)}/></Field><Field label="Canal"><select value={x.channel||'Instagram'} onChange={e=>edit(x,'channel',e.target.value)}><option>Instagram</option><option>Facebook</option><option>LinkedIn</option><option>GBP</option></select></Field><Field label="Status"><select value={x.status||'Rascunho'} onChange={e=>edit(x,'status',e.target.value)}><option>Rascunho</option><option>Em revisão</option><option>Aprovado</option><option>Publicado</option></select></Field></article>)}</div>{!filtered.length&&<div className="empty"><h3>Nenhuma publicação neste filtro.</h3><p>Gere o plano RETINA ou adicione uma publicação.</p></div>}</>;
}
const checks=[['foto','Foto ou logo nítido','Use uma imagem reconhecível em tamanho pequeno.'],['nome','Nome e especialidade claros','Identifique a marca e o que ela oferece.'],['bio','Bio com oferta e chamada para ação','Explique o benefício, a região e o próximo passo.'],['link','Destino do contato funcionando','Teste o link, o formulário e o atendimento.'],['provas','Provas e serviços visíveis','Organize serviços, casos reais e depoimentos.'],['posts','Conteúdo recente e coerente','Revise publicações e conteúdos fixados.'],['retina','Conteúdo com funções variadas','Combine educação, relacionamento e autoridade.'],['tracking','Conversões definidas','Defina como acompanhar mensagens, formulários e vendas.']];
export function Readiness({p,update}:any){const data=p.channelReadiness||{};const done=checks.filter(([id])=>data[id]).length;return <><Intro tag="ANTES DE INVESTIR" title="Prepare a marca para receber visitantes." text="Checklist informado por você, com ações práticas para cada pendência."/><Section title={`${done} de ${checks.length} verificações concluídas`}><div className="readinessList">{checks.map(([id,title,action])=><label key={id}><input type="checkbox" checked={!!data[id]} onChange={e=>update((d:any)=>{d.channelReadiness={...(d.channelReadiness||{}),[id]:e.target.checked}})}/><div><b>{title}</b><p>{data[id]?'Concluído':action}</p></div><span className={`pill ${data[id]?'green':'amber'}`}>{data[id]?'Pronto':'A revisar'}</span></label>)}</div></Section></>}
export function GoogleWorkspace({p,update,run}:any){
 const data=p.googleAds;const selected=data?.selected||[];const [newTerm,setNewTerm]=useState('');const ai=p.aiInputs||{};
 const edit=(fn:any)=>update((d:any)=>{d.googleAds=d.googleAds||{keywords:{},selected:[]};fn(d.googleAds)});
 const setAI=(k:string,v:any)=>update((d:any)=>{d.aiInputs={...(d.aiInputs||{}),[k]:v}});
 const keywords=[...new Set<string>([...(data?.keywords?.highIntent||[]),...(data?.keywords?.problemAware||[]),...selected])];
 const ready=!!(p.name?.trim()&&ai.conversionAction?.trim()&&(ai.adOffer||p.services||p.products)?.trim()&&p.location?.trim()&&p.persona);
 return <><Intro tag="ANÚNCIOS / GOOGLE" title="Primeiro a intenção. Depois a mensagem." text="O motor segue o prompt completo: marca, ação, oferta, localização e persona → palavras-chave → seleção humana → correspondências → títulos e descrições." action={<button className="primary" disabled={!ready} onClick={()=>run('googleKeywords')}>✦ Gerar palavras-chave</button>}/>
 <Section title="Informações da campanha"><div className="form2"><Field label="Produto ou serviço em foco"><input value={ai.adOffer||''} onChange={e=>setAI('adOffer',e.target.value)} placeholder={p.services||'Oferta específica'}/></Field><Field label="Ação depois do clique"><input value={ai.conversionAction||''} onChange={e=>setAI('conversionAction',e.target.value)} placeholder="Ex.: solicitar orçamento"/></Field></div><Requirements items={[[ 'Nome da marca',!!p.name?.trim()],['Ação desejada',!!ai.conversionAction?.trim()],['Oferta específica',!!(ai.adOffer||p.services||p.products)?.trim()],['Localização',!!p.location?.trim()],['Persona',!!p.persona]]}/></Section>
 {!data?<div className="empty"><h3>Encontre quem já procura pela oferta.</h3><p>Complete os cinco itens e gere 20 termos principais, 10 complementares e 10 negativas para revisão.</p></div>:<><Section title="Palavras-chave para copiar" action={<Download data={data.keywords||{}} name="palavras-chave-google"/>}><p className="muted">Um termo por linha, sem numeração: é só copiar e colar na planilha ou no Google Ads.</p><div className="grid2"><CopyBlock title="20 palavras-chave principais" hint="Da maior para a menor intenção comercial estimada." lines={data.keywords?.highIntent||[]}/><CopyBlock title="10 palavras-chave complementares" lines={data.keywords?.problemAware||[]}/><CopyBlock title="10 palavras-chave negativas" lines={data.keywords?.negative||[]}/></div></Section>
 <Section title={`1. Escolha de 5 a 8 palavras-chave · ${selected.length} selecionadas`}><div className="keywordSelection">{keywords.map(term=><label key={term}><input type="checkbox" checked={selected.includes(term)} onChange={e=>edit((g:any)=>{g.selected=e.target.checked?[...(g.selected||[]),term]:(g.selected||[]).filter((x:string)=>x!==term)})}/><span>{term}</span></label>)}</div><form className="calendarAdd" onSubmit={e=>{e.preventDefault();if(newTerm.trim())edit((g:any)=>{g.keywords={...g.keywords,highIntent:[...new Set([...(g.keywords?.highIntent||[]),newTerm.trim()])]};setNewTerm('')})}}><Field label="Adicionar palavra-chave"><input value={newTerm} onChange={e=>setNewTerm(e.target.value)}/></Field><button className="secondary">Adicionar</button></form><Field label="Negativas — uma por linha"><textarea value={(data.keywords?.negative||[]).join('\n')} onChange={e=>edit((g:any)=>{g.keywords={...g.keywords,negative:e.target.value.split('\n').filter(Boolean)}})}/></Field></Section><Section title="2. Correspondências e textos"><div className="form2"><CopyBlock title="Correspondência de frase" lines={data.phraseMatch?.length?data.phraseMatch:selected.map((s:string)=>`"${s}"`)}/><CopyBlock title="Correspondência exata" lines={data.exactMatch?.length?data.exactMatch:selected.map((s:string)=>`[${s}]`)}/></div><button className="primary" disabled={selected.length<5||selected.length>8} onClick={()=>run('googleAds',{selectedKeywords:selected})}>✦ Gerar correspondências, 20 títulos e 8 descrições</button><p className="muted">A geração só avança após sua seleção de 5 a 8 termos, como previsto no prompt.</p></Section>{data.titles?.length>0&&<Section title="3. Ativos para revisão" action={<Download data={data} name="anuncios-google"/>}><div className="grid2"><CopyBlock title="20 títulos" hint="Máximo de 30 caracteres cada, contando espaços e pontuação." lines={data.titles}/><CopyBlock title="8 descrições" hint="Máximo de 90 caracteres cada, contando espaços e pontuação." lines={data.descriptions||[]}/></div><h4>Títulos</h4><div className="adAssets">{data.titles.map((s:string,i:number)=><Field key={i} label={`Título ${i+1} · ${s.length}/30${s.length>30?' — ajuste necessário':''}`}><input value={s} onChange={e=>edit((g:any)=>{g.titles[i]=e.target.value})}/></Field>)}</div><h4>Descrições</h4>{data.descriptions?.map((s:string,i:number)=><Field key={i} label={`Descrição ${i+1} · ${s.length}/90${s.length>90?' — ajuste necessário':''}`}><textarea value={s} onChange={e=>edit((g:any)=>{g.descriptions[i]=e.target.value})}/></Field>)}</Section>}</>}</>;
}
