'use client';
import {useEffect,useRef,useState} from 'react';
import {calcBudget,investmentLevel,markArtifact,projectHealth} from '../lib/core.js';
import {printMarketingPlan} from '../lib/print-docs.js';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const categories=['Relacionamento','Engajamento','Transformação','Interação 1x1','Níveis de consciência','Autoridade'];
const uid=()=>`item-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function Field({label,children,hint}:any){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Section({title,children,action}:any){return <section className="card"><div className="cardHead"><h3>{title}</h3>{action}</div>{children}</section>}
function Intro({tag,title,text,action}:any){return <div className="sectionIntro"><div><div className="eyebrow">{tag}</div><h2>{title}</h2><p>{text}</p></div>{action}</div>}
function Text({value}:any){return <div className="fullText">{typeof value==='string'?value:JSON.stringify(value,null,2)}</div>}
function List({title,items}:any){return items?.length?<div className="docList"><h4>{title}</h4><ul>{items.map((x:any,i:number)=><li key={i}>{typeof x==='string'?x:JSON.stringify(x)}</li>)}</ul></div>:null}
function Download({data,name}:any){return <button className="secondary" onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`${name}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}>Exportar</button>}
function Requirements({items,title='Informações para este motor',note}:any){
 const done=items.filter((x:any)=>x[1]).length;
 return <div className="enginePrep"><div className="enginePrepHead"><div><small>PRÉ-REQUISITOS</small><b>{title}</b></div><span>{done}/{items.length}</span></div><div className="requirementGrid">{items.map((x:any,i:number)=><div key={i} className={x[1]?'ready':'missing'}><span>{x[1]?'✓':'○'}</span><b>{x[0]}</b></div>)}</div>{note&&<p>{note}</p>}</div>;
}


export function Projects({projects,open,create}:any){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('Todos');
 const stage=(p:any)=>p.commercialStage==='won'?'Cliente':p.commercialStage==='declined'?'Declinado':p.proposal?'Proposta':p.marketingPlan?'Plano':p.approach?'Abordagem':'Prospecção';
 const next=(p:any)=>{
  if(p.commercialStage==='declined')return 'Revisar proposta';
  if(p.commercialStage==='won'){
   if(!p.persona)return 'Criar persona';
   if(!p.content?.items?.length)return 'Criar RETINA';
   if(!(p.metaAds||p.googleAds?.titles?.length))return 'Criar anúncios';
   if(!p.mediaPlanConfirmed)return 'Distribuir investimento';
   return 'Acompanhar resultados';
  }
  if(!(p.specialty&&p.niche&&p.location))return 'Completar briefing';
  if(!p.approach)return 'Gerar abordagem';
  if(!p.marketingPlan)return 'Gerar plano';
  if(!p.proposal)return 'Gerar proposta';
  return 'Registrar decisão';
 };
 const list=projects.filter((p:any)=>`${p.name} ${p.specialty} ${p.location}`.toLowerCase().includes(query.toLowerCase())&&(filter==='Todos'||stage(p)===filter));
 return <><section className="portfolioHero"><div className="eyebrow">NEXUS MARKETING IA</div><h2>Projetos em um fluxo<br/>simples de trabalho.</h2><p>Abra um projeto e continue exatamente de onde parou.</p><button className="primary" onClick={create}>＋ Criar projeto</button><div className="portfolioDecoration" aria-hidden="true">NXS</div></section>
 <div className="portfolioToolbar"><div><h3>Meus projetos <span>{projects.length}</span></h3><p>Prospecção, fechamento e gestão no mesmo lugar.</p></div><div className="portfolioFilters"><Field label="Buscar projeto"><input type="search" placeholder="Nome, especialidade ou cidade" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Etapa"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Prospecção</option><option>Abordagem</option><option>Plano</option><option>Proposta</option><option>Cliente</option><option>Declinado</option></select></Field></div></div>
 <div className="projectGrid">{list.map((p:any)=>{const h=projectHealth(p);const s=stage(p);return <article className="projectCard" key={p.id}><div className="projectCardTop"><span className="projectMonogram">{p.name.split(' ').slice(0,2).map((s:string)=>s[0]).join('').toUpperCase()}</span><span className={`pill ${s==='Cliente'?'green':s==='Declinado'?'red':'blue'}`}>{s}</span></div><h3>{p.name}</h3><p>{p.specialty||'Briefing ainda não concluído'}</p><span className="projectLocation">{p.location||'Localização a definir'}</span><div className="projectObjective"><small>PRÓXIMO PASSO</small><b>{next(p)}</b></div><div className="projectProgress"><span>Estrutura disponível</span><b>{h.score}%</b></div><div className="progress"><i style={{width:h.score+'%'}}/></div><div className="projectCardFoot"><small>Atualizado {new Date(p.updatedAt).toLocaleDateString('pt-BR')}</small><button className="primary" onClick={()=>open(p.id)}>Continuar →</button></div></article>})}<button className="projectCreateCard" onClick={create}><span>＋</span><b>Novo projeto</b><p>Comece pela prospecção.</p></button></div>{!list.length&&<p role="status">Nenhum projeto encontrado com esses filtros.</p>}</>;
}
export function ProjectDialog({save,close}:any){
 const ref=useRef<HTMLDialogElement>(null);const [name,setName]=useState(''),[objective,setObjective]=useState('Gerar oportunidades qualificadas'),[location,setLocation]=useState('');
 useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>previous?.focus()},[]);
 return <dialog ref={ref} className="projectDialog" onCancel={e=>{e.preventDefault();close()}} aria-labelledby="project-dialog-title"><form onSubmit={e=>{e.preventDefault();if(name.trim())save({name:name.trim(),objective,location})}}><div className="cardHead"><div><div className="eyebrow">NOVA ÁREA DE TRABALHO</div><h2 id="project-dialog-title">Criar projeto</h2></div><button type="button" className="iconBtn" aria-label="Fechar criação de projeto" onClick={close}>×</button></div><p>Organize os dados e materiais de uma marca em um só lugar.</p><Field label="Nome da marca ou projeto"><input autoFocus required maxLength={100} value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nexus Digital"/></Field><Field label="Objetivo principal"><input value={objective} onChange={e=>setObjective(e.target.value)}/></Field><Field label="Cidade ou região"><input value={location} onChange={e=>setLocation(e.target.value)}/></Field><div className="buttonRow"><button className="primary" type="submit" disabled={!name.trim()}>Criar projeto</button><button className="secondary" type="button" onClick={close}>Cancelar</button></div></form></dialog>
}
export function BrandBrief({p,update,onContinue}:any){
 const set=(k:string,v:any)=>update((d:any)=>{d[k]=v;d.versions={...d.versions,business:(d.versions?.business||0)+1}});
 const input=(k:string,label:string,multiline=false,placeholder='')=><Field key={k} label={label}>{multiline?<textarea value={p[k]||''} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>:<input value={p[k]||''} onChange={e=>set(k,e.target.value)} placeholder={placeholder}/>}</Field>;
 const ready=!!(p.name?.trim()&&p.specialty?.trim()&&p.niche?.trim()&&p.location?.trim());
 const uploadLogo=(file?:File)=>{if(!file)return;if(file.size>700000){alert('Use uma logo de até 700 KB para evitar falhas de armazenamento no navegador.');return}const reader=new FileReader();reader.onload=()=>set('brandLogo',String(reader.result||''));reader.readAsDataURL(file)};
 return <><Intro tag="ETAPA 1 DE 5 · PROSPECÇÃO" title="Conheça a empresa antes de abordar." text="Preencha a base do prospect. O restante do fluxo reaproveita estas informações."/>
 <div className="workspaceColumns"><Section title="Empresa">{input('name','Nome da empresa')}{input('specialty','O que ela vende ou presta',true,'Serviços, produtos e especialidades')}{input('niche','Quem costuma comprar',true,'Público, tipo de cliente ou segmento')}{input('description','Contexto do negócio',true,'Resumo objetivo da empresa')}{input('location','Cidade ou região')}</Section><div className="stack"><Section title="Oferta">{input('services','Serviços principais',true)}{input('products','Produtos, se houver',true)}{input('offers','Diferenciais, garantias ou condições conhecidas',true)}{input('objective','Objetivo desta prospecção')}</Section><Section title="Identidade"><div className="brandIdentityRow"><div className="brandLogoPreview">{p.brandLogo?<img src={p.brandLogo} alt="Logo do prospect"/>:<span>LOGO</span>}</div><div><Field label="Logo da empresa" hint="PNG ou JPG, até 700 KB."><input type="file" accept="image/png,image/jpeg" onChange={e=>uploadLogo(e.target.files?.[0])}/></Field>{p.brandLogo&&<button className="dangerText" onClick={()=>set('brandLogo','')}>Remover logo</button>}</div></div><div className="form2"><Field label="Cor principal"><input type="color" value={/^#[0-9a-f]{6}$/i.test(p.brandColor||'')?p.brandColor:'#002e6c'} onChange={e=>set('brandColor',e.target.value)}/></Field>{input('tone','Tom de voz')}</div>{input('contactDestination','Site, Instagram, Google ou WhatsApp',true)}</Section></div></div>
 <div className="flowFooter"><div><b>{ready?'Briefing pronto':'Complete os campos essenciais'}</b><span>{ready?'A próxima etapa é preparar a abordagem.':'Nome, oferta, público e localização são obrigatórios.'}</span></div><button className="primary" disabled={!ready} onClick={onContinue}>Salvar e seguir →</button></div>
 </>;
}
export function MediaPlanning({p,update,onContinue}:any){
 const b={...p.budget,gbpPct:p.budget?.gbpPct??20};const total=calcBudget(b.amount,b.demand,b.level,b.gbpPct,b.googleOverride);
 const set=(k:string,v:any)=>update((d:any)=>{d.budget={...d.budget,[k]:v};d.mediaPlanConfirmed=false;if(k==='amount')d.budget.level=investmentLevel(v)});
 const finish=()=>{update((d:any)=>{d.mediaPlanConfirmed=true},'Distribuição de investimento confirmada');onContinue?.()};
 return <><Intro tag="ETAPA 4 DE 5 · GESTÃO" title="Distribua o investimento sem precisar dominar mídia paga." text="Informe o orçamento e como a demanda acontece. O Nexus aplica a matriz e mostra a divisão."/>
 <div className="workspaceColumns"><Section title="Defina o cenário"><Field label="Investimento mensal disponível (R$)"><input type="number" min="0" step="50" value={b.amount||''} onChange={e=>set('amount',Math.max(0,Number(e.target.value)))}/></Field><Field label="Como as pessoas chegam até esta empresa?"><select value={b.demand} onChange={e=>set('demand',e.target.value)}><option value="busca">Já estão procurando pelo serviço</option><option value="descoberta">Precisamos despertar interesse</option><option value="hibrido">Os dois cenários</option></select></Field><div className="matrixSummary"><span>Google <b>{total.googlePct}%</b></span><span>Meta <b>{total.metaPct}%</b></span><span>GBP <b>{total.gbpPct}% do Google</b></span></div><details className="advanced"><summary>Ajustes avançados</summary><Field label={`Google: ${total.googlePct}% · Meta: ${total.metaPct}%`}><input type="range" min="0" max="100" value={total.googlePct} onChange={e=>set('googleOverride',Number(e.target.value))}/></Field><Field label={`Presença local / GBP: ${total.gbpPct}% da verba Google`} hint="O padrão do Nexus é 20% da parcela destinada ao Google."><input type="range" min="0" max="100" value={total.gbpPct} onChange={e=>set('gbpPct',Number(e.target.value))}/></Field><button className="secondary" onClick={()=>update((d:any)=>{d.budget={...d.budget,googleOverride:null,gbpPct:20}})}>Restaurar recomendação</button></details></Section><div className="stack"><Section title="Distribuição sugerida"><div className="allocationTotal"><small>INVESTIMENTO TOTAL</small><b>{money.format(total.total)}</b></div><div className="allocationBar"><span style={{width:total.googlePct+'%'}}/><span style={{width:total.metaPct+'%'}}/></div><div className="allocationTiles"><div><span>Google · {total.googlePct}%</span><b>{money.format(total.google)}</b></div><div><span>Meta · {total.metaPct}%</span><b>{money.format(total.meta)}</b></div></div><div className="budgetMini"><div><small>Perfil da Empresa / GBP · {total.gbpPct}% do Google</small><b>{money.format(total.gbp)}</b></div><div><small>Demais Google Ads · {total.adsPct}% do Google</small><b>{money.format(total.ads)}</b></div></div></Section><Section title="Campanhas sugeridas"><List items={total.campaigns}/></Section></div></div>
 <div className="flowFooter"><div><b>{total.total>0?'Distribuição pronta':'Informe o orçamento'}</b><span>{total.total>0?'Depois disso, o foco passa a ser acompanhar resultado.':'O Nexus não assume uma verba sem você informar.'}</span></div><button className="primary" disabled={total.total<=0} onClick={finish}>Salvar e ir para resultados →</button></div>
 </>;
}
export function PlanWorkspace({p,update,run,onContinue,settings}:any){
 const data=p.marketingPlan; const ai=p.aiInputs||{};
 const setAI=(k:string,v:any)=>update((d:any)=>{d.aiInputs={...(d.aiInputs||{}),[k]:v}});
 const material=[
  ['Empresa e oferta',!!(p.name&&p.location&&(p.specialty||p.services||p.products))],
  ['Contexto da prospecção',!!(ai.planApproachContext||p.approach)?.toString().trim()],
  ['Destinatário',!!(ai.planRecipientProfile||ai.decisionMakerContext||ai.prospectOwner)?.toString().trim()],
  ['Identidade',!!(p.brandLogo||p.brandColor)],
  ['Condições conhecidas',!!(ai.operationalDetails||p.offers)?.toString().trim()],
  ['Contato para assinatura',!!((ai.signerName||settings?.managerName||'').trim()&&(ai.signerWhatsapp||settings?.agencyWhatsapp||'').trim())]
 ];
 const hasClient=!!(data?.client&&(data.client.personaName||data.client.summary||data.client.obstacle||(data.client.fears||[]).length||(data.client.objections||[]).length));
 const hasAwareness=Array.isArray(data?.awareness)&&data.awareness.length>0;
 const hasPositioning=!!(data?.positioning&&((data.positioning.commitments||[]).length||(data.positioning.fearResponses||[]).length));
 let pageNo=0;
 const page=(title:string,children:any)=>{const n=String(++pageNo).padStart(2,'0');return <section className="planPage"><div className="planPageNo">{n}</div><div><small>PLANO DE MARKETING</small><h3>{title}</h3>{children}</div></section>};
 return <><Intro tag="ETAPA 3 DE 5 · PROSPECÇÃO" title="Transforme o diagnóstico em um plano apresentável." text="O Nexus usa o briefing e a abordagem. Complete somente o contexto comercial que ainda falta." action={<button className="primary" onClick={()=>run('marketingPlan',{context:p.planContext,manager:settings})}>✦ {data?'Gerar nova versão':'Gerar plano'}</button>}/>
 <Requirements items={material} title="Informações reunidas" note="Itens opcionais ausentes não travam a geração; o Nexus simplesmente não inventa o que não foi informado."/>
 <details className="contextDetails" open={!data}><summary>Completar informações específicas do plano</summary><div className="form2"><Field label="Contexto da prospecção"><textarea value={ai.planApproachContext||''} onChange={e=>setAI('planApproachContext',e.target.value)} placeholder="Contato frio, conversa anterior, indicação, o que já foi dito..."/></Field><Field label="Quem receberá o material"><textarea value={ai.planRecipientProfile||''} onChange={e=>setAI('planRecipientProfile',e.target.value)} placeholder="Dono, gerente, o que valoriza, o que já tentou, o que incomoda..."/></Field></div><Field label="Condições atuais conhecidas" hint="Garantia, taxa de visita, horários, área atendida, formas de pagamento. Se não souber, deixe em branco."><textarea value={ai.operationalDetails||''} onChange={e=>setAI('operationalDetails',e.target.value)}/></Field><Field label="Outros materiais ou informações"><textarea value={ai.additionalMaterials||p.planContext||''} onChange={e=>{setAI('additionalMaterials',e.target.value);update((d:any)=>{d.planContext=e.target.value})}} placeholder="Avaliações, prints, dados internos, observações..."/></Field><div className="form2"><Field label="Nome para assinatura"><input value={ai.signerName||settings?.managerName||''} onChange={e=>setAI('signerName',e.target.value)}/></Field><Field label="Cargo / assinatura"><input value={ai.signerRole||settings?.managerSpecialty||''} onChange={e=>setAI('signerRole',e.target.value)}/></Field></div><Field label="WhatsApp com DDD"><input value={ai.signerWhatsapp||settings?.agencyWhatsapp||''} onChange={e=>setAI('signerWhatsapp',e.target.value)} placeholder="15999999999"/></Field><Field label="Convite final opcional"><textarea value={ai.invitationText||''} onChange={e=>setAI('invitationText',e.target.value)} placeholder="Se deixar vazio, o próprio prompt escreve o convite."/></Field></details>
 {!data?<section className="empty"><h3>O plano ainda não foi gerado.</h3><p>Quanto mais itens acima estiverem preenchidos, mais específico será o documento. Você pode gerar mesmo com itens opcionais ausentes.</p></section>:<div className="planPages">
 {page('Capa',<>{p.brandLogo&&<img className="planClientLogo" src={p.brandLogo} alt="Logo do cliente"/>}<h2>{data.cover?.company||p.name}</h2><p>{data.cover?.objective}</p><div className="tagRow"><span>{data.cover?.city}</span><span>{data.cover?.period}</span><span>{data.cover?.conversion}</span></div></>)}
 {page('O que este plano propõe',<><p>{data.proposal?.text}</p>{data.proposal?.communicationPromise&&<blockquote className="planHighlight">{data.proposal.communicationPromise}</blockquote>}<div className="planRows">{(data.proposal?.workstreams||[]).map((x:any,i:number)=><div key={i}><b>{x.channel}</b><span>{x.audience}</span><p>{x.role}</p></div>)}</div></>)}
 {(data.marketContext?.facts?.length||data.marketContext?.practicalNote)&&page('Contexto de mercado',<><div className="planFacts">{(data.marketContext?.facts||[]).map((x:any,i:number)=><div key={i}><b>{x.value}</b><span>{x.label}</span><small>{x.note}</small></div>)}</div><p>{data.marketContext?.practicalNote}</p></>)}
 {hasClient&&page('Quem é o cliente',<><h4>{data.client?.personaName}</h4><p>{data.client?.summary}</p><List title="Medos" items={data.client?.fears}/><List title="Objeções" items={data.client?.objections}/><List title="O que já tentou" items={data.client?.previousAttempts}/><small className="muted">{data.client?.hypothesisNotice}</small></>)}
 {hasAwareness&&page('Os momentos até a contratação',<div className="awarenessList">{(data.awareness||[]).map((x:any,i:number)=><div key={i}><span>{i+1}</span><div><b>{x.stage}</b><p>{x.message}</p><small>{x.channel}{x.searches?.length?' · '+x.searches.join(' · '):''}</small></div></div>)}</div>)}
 {hasPositioning&&page('Posicionamento',<><List title="Compromissos de atendimento" items={data.positioning?.commitments}/><div className="planRows">{(data.positioning?.fearResponses||[]).map((x:any,i:number)=><div key={i}><b>{x.fearOrObjection}</b><p>{x.response}</p></div>)}</div></>)}
 {page('Canal por canal',<div className="planChannelGrid">{(data.channels||[]).map((x:any,i:number)=><div key={i}><h4>{x.name}</h4><p>{x.summary}</p><List items={x.items}/>{x.example&&<div className="planExample">{x.example}</div>}</div>)}</div>)}
 {page('Onde a venda acontece',<><div className="salesFlow">{(data.salesFlow?.steps||[]).map((x:string,i:number)=><div key={i}><span>{i+1}</span><b>{x}</b></div>)}</div><List title="Respostas rápidas" items={data.salesFlow?.quickReplies}/></>)}
 {page('Ordem sugerida de ativação',<><div className="activationGrid">{(data.activation?.timeline||[]).map((x:any,i:number)=><div key={i}><b>{x.period}</b><List items={x.actions}/></div>)}</div><List title="Indicadores para acompanhar" items={data.activation?.indicators}/></>)}
 {page(data.invitation?.title||'Se quiser conversar sobre isso',<><p>{data.invitation?.text}</p>{data.invitation?.whatsappNumber&&<div className="planContact"><b>WhatsApp</b><span>{data.invitation.whatsappNumber}</span><small>{data.invitation.whatsappMessage}</small></div>}<p><b>{data.invitation?.signature}</b></p></>)}
 <div className="planActions"><button className="secondary" onClick={()=>{try{printMarketingPlan(p,data)}catch(e:any){alert(e.message||'Não foi possível abrir a exportação.')}}}>Exportar PDF</button><button className="primary" onClick={onContinue}>Continuar para proposta →</button>{data.sendSeparately?.length>0&&<span>Enviar à parte: {data.sendSeparately.join(', ')}</span>}</div>
 </div>}
 </>;
}
const personaLabels:any={nome:'Nome fictício',idade:'Idade',descricao_breve:'Descrição',profissao:'Profissão',problema_principal:'Problema principal',obstaculo_principal:'Obstáculo',meta_principal:'Objetivo',sonho_principal:'Desejo principal',medos:'Medos',objecoes:'Objeções',emocoes:'Emoções',tentativas_passadas:'Soluções já tentadas',localizacao:'Localização'};
export function PersonaWorkspace({p,update,run,onContinue}:any){
 const data=p.persona;const [editing,setEditing]=useState(false);const saved=p.personas||[];
 const edit=(k:string,v:any)=>update((d:any)=>{d.persona={...d.persona,[k]:v};markArtifact(d,'persona')});
 return <><Intro tag="MARCA E PÚBLICO" title="Quem você quer alcançar?" text="A persona selecionada orienta os conteúdos e anúncios do projeto." action={<button className="primary" onClick={()=>run('persona')}>✦ {data?'Gerar nova persona':'Gerar persona'}</button>}/><div className="personaToolbar"><Field label="Persona ativa"><select value="" onChange={e=>{if(e.target.value)update((d:any)=>{d.persona=JSON.parse(JSON.stringify(saved.find((x:any)=>x.id===e.target.value).data));markArtifact(d,'persona')},'Persona selecionada')}}><option value="">{data?.nome||'Selecione uma persona salva'}</option>{saved.map((x:any)=><option key={x.id} value={x.id}>{x.data.nome} — {x.data.profissao}</option>)}</select></Field><button className="secondary" onClick={()=>{if(!data)update((d:any)=>{d.persona={nome:'Nova persona',descricao_breve:''};markArtifact(d,'persona')});setEditing(!editing)}}>{editing?'Concluir edição':'Cadastrar / editar'}</button>{data&&<button className="secondary" onClick={()=>update((d:any)=>{d.personas=[...(d.personas||[]),{id:uid(),data:JSON.parse(JSON.stringify(d.persona))}]},'Persona salva na biblioteca')}>Salvar na biblioteca</button>}</div>{data?<Section title={data.nome||'Persona'} action={<span className="pill amber">Hipótese de público · valide com clientes</span>}><div className="personaFields">{Object.entries(personaLabels).map(([k,label]:any)=><div key={k}>{editing?<Field label={label}><textarea value={Array.isArray(data[k])?data[k].join('\n'):data[k]||''} onChange={e=>edit(k,['medos','objecoes','emocoes'].includes(k)?e.target.value.split('\n'):e.target.value)}/></Field>:<><h4>{label}</h4><Text value={Array.isArray(data[k])?data[k].join('\n'):data[k]||'A completar'}/></>}</div>)}</div><details className="advanced"><summary>Perfil completo e aprofundamento</summary>{Object.entries(data).filter(([k])=>!personaLabels[k]&&k!=='niveis_consciencia').map(([k,v])=><div key={k}><h4>{k.replaceAll('_',' ')}</h4><Text value={v}/></div>)}</details><h3>Níveis de consciência</h3><div className="awarenessGrid">{Object.entries(data.niveis_consciencia||{}).map(([stage,values]:any)=><details key={stage}><summary>{stage.replaceAll('_',' ')}</summary>{Object.entries(values).map(([k,v])=><div key={k}><h4>{k.replaceAll('_',' ')}</h4><Text value={v}/></div>)}</details>)}</div><div className="buttonRow"><button className="secondary" onClick={()=>run('deepDive')}>✦ Aprofundar dores e desejos</button><button className="primary" onClick={onContinue}>Continuar para RETINA →</button></div></Section>:<section className="empty"><h3>Conheça a pessoa por trás da decisão.</h3><p>Gere uma hipótese de persona ou cadastre os dados que já conhece.</p></section>}</>;
}
export function ContentWorkspace({p,update,run,onContinue}:any){
 const [selected,setSelected]=useState<number|null>(null),[filter,setFilter]=useState('Todas'),[notice,setNotice]=useState('');const items=p.content?.items||[];const item=selected===null?null:items[selected];const ai=p.aiInputs||{};
 const edit=(k:string,v:any)=>update((d:any)=>{d.content.items[selected!][k]=v});
 const setAI=(k:string,v:any)=>update((d:any)=>{d.aiInputs={...(d.aiInputs||{}),[k]:v}});
 const field=(k:string,label:string,multiline=true)=><Field key={k} label={label}>{multiline?<textarea className={k==='script'?'scriptEditor':''} value={item[k]||''} onChange={e=>edit(k,e.target.value)}/>:<input value={item[k]||''} onChange={e=>edit(k,e.target.value)}/>}</Field>;
 const ready=!!(ai.creatorName?.trim()&&p.niche?.trim()&&p.persona);
 return <><Intro tag="04 / CONTEÚDO RETINA" title="Conteúdo pronto, não apenas ideias." text="O motor usa o prompt RETINA completo e só roda depois de saber quem cria, qual é o nicho e qual persona queremos alcançar." action={<button className="primary" disabled={!ready} onClick={()=>{setSelected(null);run('content')}}>✦ {p.content?'Gerar nova versão':'Gerar 6 conteúdos'}</button>}/>
 <Section title="Antes de gerar"><Field label="Nome de quem cria os conteúdos"><input value={ai.creatorName||''} onChange={e=>setAI('creatorName',e.target.value)} placeholder="Pessoa, especialista ou marca que aparecerá no conteúdo"/></Field><Requirements items={[[ 'Responsável pelo conteúdo',!!ai.creatorName?.trim()],['Nicho de mercado',!!p.niche?.trim()],['Persona detalhada',!!p.persona]]} note="O Nexus reaproveita a persona do projeto automaticamente."/></Section>
 <div className="retinaGuide">{categories.map((c,i)=><div key={c}><b>{'RETINA'[i]}</b><span>{c}</span></div>)}</div>{!items.length?<section className="empty"><h3>Seu próximo conteúdo começa na persona.</h3><p>Complete os três pré-requisitos e gere seis peças completas, uma para cada função do RETINA.</p></section>:item?<><button className="secondary backButton" onClick={()=>setSelected(null)}>← Todos os conteúdos</button><Section title={item.title} action={<button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText([item.title,item.hook,item.script,item.igCaption].join('\n\n'));setNotice('Conteúdo copiado.')}catch{setNotice('Não foi possível copiar. Use a exportação.')}}}>Copiar conteúdo</button>}><span role="status">{notice}</span><div className="form2">{field('title','Título',false)}<Field label="Categoria RETINA"><input value={item.category||''} readOnly/></Field></div><div className="form2">{field('format','Formato',false)}<Field label="Status"><select value={item.status||'Rascunho'} onChange={e=>edit('status',e.target.value)}><option>Rascunho</option><option>Em revisão</option><option>Aprovado</option><option>Publicado</option></select></Field></div>{field('idea','Ideia central')}{field('hook','Gancho')}{field('script','Roteiro completo')}{field('igCaption','Legenda')}<div className="form2">{field('dorDesejo','Dor ou desejo')}{field('objecaoDuvida','Objeção ou dúvida')}</div>{field('objetivoRetina','Objetivo dentro do RETINA')}<div className="form2"><Field label="Data prevista"><input type="date" value={item.scheduledDate||''} onChange={e=>edit('scheduledDate',e.target.value)}/></Field><Field label="Canal"><select value={item.channel||'Instagram'} onChange={e=>edit('channel',e.target.value)}><option>Instagram</option><option>Facebook</option><option>LinkedIn</option><option>GBP</option></select></Field></div></Section></>:<><div className="portfolioToolbar"><Field label="Filtrar categoria"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todas</option>{items.map((x:any,i:number)=><option key={i}>{x.category}</option>)}</select></Field><Download data={p.content} name="conteudo-retina"/></div><div className="contentGrid">{items.map((x:any,i:number)=>(filter==='Todas'||filter===x.category)&&<Section key={i} title={x.title}><span className="pill blue">{x.category}</span><p><b>{x.hook}</b></p><p>{x.idea}</p><div className="tagRow"><span>{x.format}</span><span>{x.status||'Rascunho'}</span></div><button className="primary" onClick={()=>setSelected(i)}>Abrir roteiro e editar →</button></Section>)}</div></>}{items.length>0&&selected===null&&<div className="flowFooter"><div><b>Conteúdo estruturado</b><span>Agora escolha onde a empresa vai anunciar.</span></div><button className="primary" onClick={onContinue}>Continuar para anúncios →</button></div>}</>;
}
export function CalendarWorkspace({p,update}:any){
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[query,setQuery]=useState('Todos'),[title,setTitle]=useState('');
 const items=[...(p.content?.items||[]).map((x:any,i:number)=>({...x,index:i,kind:'content'})),...(p.calendarItems||[]).map((x:any,i:number)=>({...x,index:i,kind:'calendar'}))];
 const edit=(x:any,k:string,v:any)=>update((d:any)=>{(x.kind==='content'?d.content.items:d.calendarItems)[x.index][k]=v});
 const filtered=items.filter(x=>(!x.scheduledDate||x.scheduledDate.startsWith(month))&&(query==='Todos'||(x.status||'Rascunho')===query)).sort((a,b)=>(a.scheduledDate||'9999').localeCompare(b.scheduledDate||'9999'));
 return <><Intro tag="05 / EXECUÇÃO" title="O que vai ao ar, e quando." text="Organize produção e revisão por projeto. As datas registram o planejamento editorial."/><div className="calendarFilters"><Field label="Mês"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field><Field label="Status"><select value={query} onChange={e=>setQuery(e.target.value)}><option>Todos</option><option>Rascunho</option><option>Em revisão</option><option>Aprovado</option><option>Publicado</option></select></Field></div><Section title="Adicionar publicação"><form className="calendarAdd" onSubmit={e=>{e.preventDefault();if(title.trim()){update((d:any)=>{d.calendarItems=[...(d.calendarItems||[]),{id:uid(),title:title.trim(),status:'Rascunho',channel:'Instagram',scheduledDate:''}]});setTitle('')}}}><Field label="Título da publicação"><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><button className="primary">Adicionar</button></form></Section><div className="calendarList">{filtered.map(x=><article className="card calendarRow" key={`${x.kind}-${x.index}`}><div><small>{x.category||'PUBLICAÇÃO'}</small><h3>{x.title}</h3></div><Field label="Data prevista"><input type="date" value={x.scheduledDate||''} onChange={e=>edit(x,'scheduledDate',e.target.value)}/></Field><Field label="Canal"><select value={x.channel||'Instagram'} onChange={e=>edit(x,'channel',e.target.value)}><option>Instagram</option><option>Facebook</option><option>LinkedIn</option><option>GBP</option></select></Field><Field label="Status"><select value={x.status||'Rascunho'} onChange={e=>edit(x,'status',e.target.value)}><option>Rascunho</option><option>Em revisão</option><option>Aprovado</option><option>Publicado</option></select></Field></article>)}</div>{!filtered.length&&<div className="empty"><h3>Nenhuma publicação neste filtro.</h3><p>Gere o plano RETINA ou adicione uma publicação.</p></div>}</>;
}
const checks=[['foto','Foto ou logo nítido','Use uma imagem reconhecível em tamanho pequeno.'],['nome','Nome e especialidade claros','Identifique a marca e o que ela oferece.'],['bio','Bio com oferta e chamada para ação','Explique o benefício, a região e o próximo passo.'],['link','Destino do contato funcionando','Teste o link, o formulário e o atendimento.'],['provas','Provas e serviços visíveis','Organize serviços, casos reais e depoimentos.'],['posts','Conteúdo recente e coerente','Revise publicações e conteúdos fixados.'],['retina','Conteúdo com funções variadas','Combine educação, relacionamento e autoridade.'],['tracking','Conversões definidas','Defina como acompanhar mensagens, formulários e vendas.']];
export function Readiness({p,update}:any){const data=p.channelReadiness||{};const done=checks.filter(([id])=>data[id]).length;return <><Intro tag="ANTES DE INVESTIR" title="Prepare a marca para receber visitantes." text="Checklist informado por você, com ações práticas para cada pendência."/><Section title={`${done} de ${checks.length} verificações concluídas`}><div className="readinessList">{checks.map(([id,title,action])=><label key={id}><input type="checkbox" checked={!!data[id]} onChange={e=>update((d:any)=>{d.channelReadiness={...(d.channelReadiness||{}),[id]:e.target.checked}})}/><div><b>{title}</b><p>{data[id]?'Concluído':action}</p></div><span className={`pill ${data[id]?'green':'amber'}`}>{data[id]?'Pronto':'A revisar'}</span></label>)}</div></Section></>}
export function GoogleWorkspace({p,update,run}:any){
 const data=p.googleAds;const selected=data?.selected||[];const [newTerm,setNewTerm]=useState('');const ai=p.aiInputs||{};
 const edit=(fn:any)=>update((d:any)=>{d.googleAds=d.googleAds||{keywords:{},selected:[]};fn(d.googleAds)});
 const setAI=(k:string,v:any)=>update((d:any)=>{d.aiInputs={...(d.aiInputs||{}),[k]:v}});
 const keywords=[...new Set<string>([...(data?.keywords?.highIntent||[]),...(data?.keywords?.problemAware||[]),...selected])];
 const ready=!!(p.name?.trim()&&ai.conversionAction?.trim()&&(ai.adOffer||p.services||p.products)?.trim()&&p.location?.trim()&&p.persona);
 return <><Intro tag="ANÚNCIOS / GOOGLE" title="Primeiro a intenção. Depois a mensagem." text="O motor segue o prompt completo: marca, ação, oferta, localização e persona → palavras-chave → seleção humana → correspondências → títulos e descrições." action={<button className="primary" disabled={!ready} onClick={()=>run('googleKeywords')}>✦ Gerar palavras-chave</button>}/>
 <Section title="Informações da campanha"><div className="form2"><Field label="Produto ou serviço em foco"><input value={ai.adOffer||''} onChange={e=>setAI('adOffer',e.target.value)} placeholder={p.services||'Oferta específica'}/></Field><Field label="Ação depois do clique"><input value={ai.conversionAction||''} onChange={e=>setAI('conversionAction',e.target.value)} placeholder="Ex.: solicitar orçamento"/></Field></div><Requirements items={[[ 'Nome da marca',!!p.name?.trim()],['Ação desejada',!!ai.conversionAction?.trim()],['Oferta específica',!!(ai.adOffer||p.services||p.products)?.trim()],['Localização',!!p.location?.trim()],['Persona',!!p.persona]]}/></Section>
 {!data?<div className="empty"><h3>Encontre quem já procura pela oferta.</h3><p>Complete os cinco itens e gere 20 termos principais, 10 complementares e 10 negativas para revisão.</p></div>:<><Section title={`1. Escolha de 5 a 8 palavras-chave · ${selected.length} selecionadas`}><div className="keywordSelection">{keywords.map(term=><label key={term}><input type="checkbox" checked={selected.includes(term)} onChange={e=>edit((g:any)=>{g.selected=e.target.checked?[...(g.selected||[]),term]:(g.selected||[]).filter((x:string)=>x!==term)})}/><span>{term}</span></label>)}</div><form className="calendarAdd" onSubmit={e=>{e.preventDefault();if(newTerm.trim())edit((g:any)=>{g.keywords={...g.keywords,highIntent:[...new Set([...(g.keywords?.highIntent||[]),newTerm.trim()])]};setNewTerm('')})}}><Field label="Adicionar palavra-chave"><input value={newTerm} onChange={e=>setNewTerm(e.target.value)}/></Field><button className="secondary">Adicionar</button></form><Field label="Negativas — uma por linha"><textarea value={(data.keywords?.negative||[]).join('\n')} onChange={e=>edit((g:any)=>{g.keywords={...g.keywords,negative:e.target.value.split('\n').filter(Boolean)}})}/></Field></Section><Section title="2. Correspondências e textos"><div className="form2"><div><h4>Frase</h4><Text value={(data.phraseMatch?.length?data.phraseMatch:selected.map((s:string)=>`"${s}"`)).join('\n')}/></div><div><h4>Exata</h4><Text value={(data.exactMatch?.length?data.exactMatch:selected.map((s:string)=>`[${s}]`)).join('\n')}/></div></div><button className="primary" disabled={selected.length<5||selected.length>8} onClick={()=>run('googleAds',{selectedKeywords:selected})}>✦ Gerar correspondências, 20 títulos e 8 descrições</button><p className="muted">A geração só avança após sua seleção de 5 a 8 termos, como previsto no prompt.</p></Section>{data.titles?.length>0&&<Section title="3. Ativos para revisão" action={<Download data={data} name="anuncios-google"/>}><h4>Títulos</h4><div className="adAssets">{data.titles.map((s:string,i:number)=><Field key={i} label={`Título ${i+1} · ${s.length}/30${s.length>30?' — ajuste necessário':''}`}><input value={s} onChange={e=>edit((g:any)=>{g.titles[i]=e.target.value})}/></Field>)}</div><h4>Descrições</h4>{data.descriptions?.map((s:string,i:number)=><Field key={i} label={`Descrição ${i+1} · ${s.length}/90${s.length>90?' — ajuste necessário':''}`}><textarea value={s} onChange={e=>edit((g:any)=>{g.descriptions[i]=e.target.value})}/></Field>)}</Section>}</>}</>;
}
